### ISSUE TITLE
Event log from malfunction

### ISSUE THREAD

**Issue by robocorpse** [ChromaControl/ChromaControl#100]
Here are some event logs related to my previously reported behaviors. 

Faulting application name: ChromaControl.Asus.exe, version: 1.0.0.0, time stamp: 0x5fd43c92
Faulting module name: coreclr.dll, version: 5.0.220.61120, time stamp: 0x5fd42cad
Exception code: 0xc0000005
Fault offset: 0x00000000001d01bf
Faulting process id: 0x49c8
Faulting application start time: 0x01d7656ece774583
Faulting application path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
Faulting module path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\coreclr.dll
Report Id: 1a61e841-bbe3-4de4-b588-3eb804086d33
Faulting package full name: ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg
Faulting package-relative application ID: App

________________

Application: ChromaControl.Asus.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC19C501BF (00007FFC19A80000) with exit code c0000005.

____________

Application: ChromaControl.Asus.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed. (0x800706BE)
   at AuraServiceLib.IAuraSyncDevice.Apply()
   at ChromaControl.Shared.Worker.Api_ColorChanged(Object sender, RzChromaBroadcastColorChangedEventArgs e)
   at Razer.Chroma.Broadcast.RzChromaBroadcastAPI.EventNotificationCallback(Int32 message, IntPtr data)

____________

Faulting application name: ChromaControl.Asus.exe, version: 1.0.0.0, time stamp: 0x5fd43c92
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0x924f9cdb
Exception code: 0xe0434352
Fault offset: 0x0000000000034b89
Faulting process id: 0x5120
Faulting application start time: 0x01d764add5921369
Faulting application path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 6266200b-47b6-422d-8cb8-b0d0f33ce659
Faulting package full name: ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg
Faulting package-relative application ID: App

_____________

Application: ChromaControl.Asus.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: The process cannot access the file 'C:\Users\########\AppData\Local\ChromaControl\logs\ASUS.log' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at NReco.Logging.File.FileLoggerProvider.FileWriter.OpenFile(Boolean append)
   at NReco.Logging.File.FileLoggerProvider.FileWriter..ctor(FileLoggerProvider fileLogPrv)
   at NReco.Logging.File.FileLoggerProvider..ctor(String fileName, FileLoggerOptions options)
   at NReco.Logging.File.FileLoggerProvider..ctor(String fileName, Boolean append)
   at Microsoft.Extensions.Logging.FileLoggerExtensions.<>c__DisplayClass0_0.<AddFile>b__0(IServiceProvider srvPrv)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ChromaControl.Asus.Program.Main(String[] args)

_______________________

Faulting application name: ChromaControl.Asus.exe, version: 1.0.0.0, time stamp: 0x5fd43c92
Faulting module name: coreclr.dll, version: 5.0.220.61120, time stamp: 0x5fd42cad
Exception code: 0xc0000005
Fault offset: 0x00000000001d01bf
Faulting process id: 0x5fc
Faulting application start time: 0x01d763b55a4a1ad6
Faulting application path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\ChromaControl.Asus.exe
Faulting module path: C:\Program Files\WindowsApps\ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg\ChromaControl.Asus\coreclr.dll
Report Id: 1c360225-a89e-40cc-bfa0-a2008d72059e
Faulting package full name: ChromaControl.Asus_1.0.0.0_x64__846pf09jn2fpg
Faulting package-relative application ID: App

______________________________

Application: ChromaControl.Asus.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFDF32E01BF (00007FFDF3110000) with exit code c0000005.

___________________________

Application: ChromaControl.Asus.exe
CoreCLR Version: 5.0.220.61120
.NET Version: 5.0.2
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException (0x800706BE): The remote procedure call failed. (0x800706BE)
   at AuraServiceLib.IAuraSyncDevice.Apply()
   at ChromaControl.Shared.Worker.Api_ColorChanged(Object sender, RzChromaBroadcastColorChangedEventArgs e)
   at Razer.Chroma.Broadcast.RzChromaBroadcastAPI.EventNotificationCallback(Int32 message, IntPtr data)

This is about 2-3 days worth of events.

**Comment by AndrewBabbitt97** [comment]
Exception was a COMException, meaning that AURA didn't register it's com component in windows correctly. 

Please reinstall Armory Crate.

**Comment by robocorpse** [comment]
I did. And then chromacontrol crashed when I shutdown the pc, similar to before.

**Comment by robocorpse** [comment]
I will get an event log tomorrow evening when I boot it up again.

**Comment by AndrewBabbitt97** [comment]
Will be solved once #77 is implemented.
